# to read and manipulate images
from PIL import Image

# this file is generated by protoc -- utility to compyle .proto file descriptions to language-specific handing code
# python example generated from http://abra.me/place/diff.proto see at http://abra.me/place/diff_pb2.py
from diff_pb2 import Diff, Pixel

import os
from datetime import datetime

# this one is optional, but I love this lib
import tqdm

# function to read a diff file
def read_diff(filename):
    with open(filename, 'rb') as file:
        b = file.read()
    return Diff.FromString(b)

def apply_diff(im_pixels, diff):
    for pixel in diff.pixel:
        im_pixels[pixel.x, pixel.y] = (pixel.r, pixel.g, pixel.b)

# let's read the base image
base_im = Image.open('diffs/base.png')
base_pixels = base_im.load()

# let's list the diff files
diff_filenames = os.listdir('diffs')
diff_filenames = sorted([os.path.join('diffs', i) for i in diff_filenames if i.endswith('bin')])
len(diff_filenames)

current_im = base_im.copy()
current_pixels = current_im.load()

for filename in tqdm.tqdm(diff_filenames):
    diff = read_diff(filename)
    apply_diff(current_pixels, diff)
