# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/misc/place/diff.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/misc/place/diff.proto',
  package='',
  serialized_pb=_b('\n\x19src/misc/place/diff.proto\">\n\x05Pixel\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\t\n\x01r\x18\x03 \x02(\x05\x12\t\n\x01g\x18\x04 \x02(\x05\x12\t\n\x01\x62\x18\x05 \x02(\x05\"I\n\x04\x44iff\x12\x15\n\rfromTimestamp\x18\x01 \x02(\x05\x12\x13\n\x0btoTimestamp\x18\x02 \x02(\x05\x12\x15\n\x05pixel\x18\x03 \x03(\x0b\x32\x06.Pixel')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PIXEL = _descriptor.Descriptor(
  name='Pixel',
  full_name='Pixel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Pixel.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Pixel.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r', full_name='Pixel.r', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g', full_name='Pixel.g', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='Pixel.b', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=91,
)


_DIFF = _descriptor.Descriptor(
  name='Diff',
  full_name='Diff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromTimestamp', full_name='Diff.fromTimestamp', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toTimestamp', full_name='Diff.toTimestamp', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pixel', full_name='Diff.pixel', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=166,
)

_DIFF.fields_by_name['pixel'].message_type = _PIXEL
DESCRIPTOR.message_types_by_name['Pixel'] = _PIXEL
DESCRIPTOR.message_types_by_name['Diff'] = _DIFF

Pixel = _reflection.GeneratedProtocolMessageType('Pixel', (_message.Message,), dict(
  DESCRIPTOR = _PIXEL,
  __module__ = 'src.misc.place.diff_pb2'
  # @@protoc_insertion_point(class_scope:Pixel)
  ))
_sym_db.RegisterMessage(Pixel)

Diff = _reflection.GeneratedProtocolMessageType('Diff', (_message.Message,), dict(
  DESCRIPTOR = _DIFF,
  __module__ = 'src.misc.place.diff_pb2'
  # @@protoc_insertion_point(class_scope:Diff)
  ))
_sym_db.RegisterMessage(Diff)


# @@protoc_insertion_point(module_scope)
