# to read and manipulate images
from PIL import Image

# this file is generated by protoc -- utility to compyle .proto file descriptions to language-specific handing code
# python example generated from http://abra.me/place/diff.proto see at http://abra.me/place/diff_pb2.py
from diff_pb2 import Diff, Pixel

import sys
import os
import numpy as np
from datetime import datetime

# this one is optional, but I love this lib
import tqdm

import imageio
import cv2

# function to read a diff file
def read_diff(filename):
    with open(filename, 'rb') as file:
        b = file.read()
    return Diff.FromString(b)

def apply_diff(im_pixels, diff):
    for pixel in diff.pixel:
        im_pixels[pixel.x, pixel.y] = (pixel.r, pixel.g, pixel.b)

if __name__ == "__main__":
    # let's read the base image
    base_im = Image.open('/diffs/base.png')
    base_pixels = base_im.load()

    # let's list the diff files
    diff_filenames = os.listdir('/diffs')
    diff_filenames = sorted([os.path.join('/diffs', i) for i in diff_filenames if i.endswith('bin')])
    len(diff_filenames)

    current_im = base_im.copy()
    current_pixels = current_im.load()

    # Define the codec and create VideoWriter object
    fourcc = cv2.VideoWriter_fourcc(*'X264')
    out = cv2.VideoWriter('output.avi',fourcc, 20.0, (1000,1000), True)

    count = 0
    for filename in tqdm.tqdm(diff_filenames):
        if count % 100 == 0:
            tqdm.tqdm.write('add image %s' % count)
            out.write(np.asarray(current_im))

        diff = read_diff(filename)
        apply_diff(current_pixels, diff)
        count += 1
        if count > 1000:
            break

    out.release()
